services:
  indexer:
    build: .
    ports:
      - "9090:8081"
    environment:
      - DATABASE__USERNAME=${DB_USERNAME:-postgres}
      - DATABASE__PASSWORD=${DB_PASSWORD}
      - DATABASE__HOST=postgres
      - DATABASE__PORT=${DB_PORT:-5432}
      - DATABASE__DATABASE_NAME=${DB_NAME:-archindexer}
      - DATABASE__MAX_CONNECTIONS=${DB_MAX_CONNECTIONS:-20}
      - DATABASE__MIN_CONNECTIONS=${DB_MIN_CONNECTIONS:-5}
      - APPLICATION__PORT=8081
      - APPLICATION__HOST=0.0.0.0
      - ARCH_NODE__URL=${ARCH_NODE_URL:-http://44.196.173.35:8081}
      - ARCH_NODE__WEBSOCKET_URL=${ARCH_NODE_WEBSOCKET_URL:-ws://44.196.173.35:10081}
      - REDIS__URL=redis://redis:6379
      - INDEXER__BATCH_SIZE=100
      - INDEXER__CONCURRENT_BATCHES=5
      - WEBSOCKET__ENABLED=true
      - WEBSOCKET__RECONNECT_INTERVAL_SECONDS=5
      - WEBSOCKET__MAX_RECONNECT_ATTEMPTS=10
      - RUST_LOG=info
    depends_on:
      - postgres
      - redis
    networks:
      - internal
    volumes:
      - ./config.yml:/usr/local/bin/config.yml:ro

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:-archindexer}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

volumes:
  pgdata:
  redis_data:

networks:
  internal: