name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache SQLx offline data
        uses: actions/cache@v3
        with:
          path: .sqlx
          key: sqlx-${{ hashFiles('**/sqlx-data.json') }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      
      - name: Package Binary
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../arch-indexer-${{ matrix.target }}.tar.gz arch-indexer
          cd -
      
      - name: Generate Release Notes
        run: |
          cat > README.release.md << 'EOL'
          ## Environment Variables

          The following environment variables can be configured:

          - DATABASE__USERNAME: Database username
          - DATABASE__PASSWORD: Database password
          - DATABASE__HOST: Database host
          - DATABASE__PORT: Database port
          - DATABASE__DATABASE_NAME: Database name
          - ARCH_NODE__URL: Arch node URL
          - REDIS__URL: Redis URL
          - INDEXER__BATCH_SIZE: Indexer batch size (default: 100)
          - INDEXER__CONCURRENT_BATCHES: Concurrent batches (default: 5)

          Example usage:
          ```bash
          DATABASE__USERNAME=postgres \
          DATABASE__PASSWORD=your_password \
          DATABASE__HOST=localhost \
          DATABASE__PORT=5432 \
          DATABASE__DATABASE_NAME=archindexer \
          ARCH_NODE__URL=http://leader:9002 \
          REDIS__URL=redis://localhost:6379 \
          ./arch-indexer
          ```
          EOL
          cd -
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            arch-indexer-${{ matrix.target }}.tar.gz
          body_path: README.release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}